version: '3'

services:
  web:
    build:
      context: .
      dockerfile: OccamsRazorWeb.Dockerfile
    image: occamsrazor.azurecr.io/occamsrazorweb
    container_name: web
    environment:
      - MARIADB_VERSION=10.6.4
    ports:
      - "5000:5000"

  frontend:
    build:
      context: .
      dockerfile: ./OccamsRazorFrontend.Dockerfile
    image: occamsrazor.azurecr.io/occamsrazorfrontend
    container_name: frontend
    ports:
      - "8080:80"
    depends_on:
      - web
