version: '3'

services:
  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped

  databases:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "3306:3306"
    environment:
      - ACCEPT_EULA=true
    depends_on:
      - nginx

  web:
    image: occamsrazorweb
    container_name: web
    ports:
      - "5000:5000"
    expose:
      - "5000"
    depends_on:
      - nginx
      - databases

