version: '3'

services:
  databases:
    build:
      context: .
      dockerfile: ./OccamsRazorSQL.Dockerfile
    image: occamsrazor.azurecr.io/occamsrazorsql
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=true
      - SA_PASSWORD=${SA_PASSWORD}


  web:
    build:
      context: .
      dockerfile: OccamsRazorWeb.Dockerfile
    image: occamsrazor.azurecr.io/occamsrazorweb
    container_name: web
    environment:
      - CONNECTION_STRING=data source=databases,1433;Database=master;User Id=sa;Password=${SA_PASSWORD};
    ports:
      - "5000:5000"
    expose:
      - "5000"
    depends_on:
      - databases

  frontend:
    build:
      context: .
      dockerfile: ./OccamsRazorFrontend.Dockerfile
    image: occamsrazor.azurecr.io/occamsrazorfrontend
    container_name: frontend
    ports:
      - "8080:80"
    expose:
      - "8080"
    depends_on:
      - databases
      - web
