version: '3'

services:
  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped

  databases:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=true
      - SA_PASSWORD=mssq!Password3
    depends_on:
      - nginx
        #    entrypoint: ["/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "mssq!Password3", "-Q", "CREATE DATABASE OccamsRazor; GO"]


  web:
    build:
      context: .
      dockerfile: OccamsRazorWeb.Dockerfile
    image: ${WEB_IMAGE}
    container_name: web
    environment:
      - CONNECTION_STRING=data source=databases,1433;Database=master;User Id=sa;Password=mssq!Password3;
    ports:
      - "5000:5000"
    expose:
      - "5000"
    depends_on:
      - nginx
      - databases

  frontend:
    build:
      context: .
      dockerfile: ./OccamsRazorFrontend.Dockerfile
    image: ${FE_IMAGE}
    container_name: frontend
    ports:
      - "3000:3000"
    expose:
      - "3000"
    depends_on:
      - nginx
      - databases
      - web
