version: '3'

services:
  databases:
    build:
      context: .
      dockerfile: ./OccamsRazorSQL.Dockerfile
    image: occamsrazor.azurecr.io/occamsrazorsql
    ports:
      - "3306:3306"
    environment:
      - ACCEPT_EULA=true
      - MARIADB_ROOT_PASSWORD=${SA_PASSWORD}


  web:
    build:
      context: .
      dockerfile: OccamsRazorWeb.Dockerfile
    image: occamsrazor.azurecr.io/occamsrazorweb
    container_name: web
    environment:
      - CONNECTION_STRING=Server=databases,3306;Database=trivia;User=root;Password=${SA_PASSWORD};
    ports:
      - "5000:5000"
    depends_on:
      - databases

  frontend:
    build:
      context: .
      dockerfile: ./OccamsRazorFrontend.Dockerfile
    image: occamsrazor.azurecr.io/occamsrazorfrontend
    container_name: frontend
    ports:
      - "8080:80"
    depends_on:
      - databases
      - web
