version: '3'

services:
  databases:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=true
      - SA_PASSWORD=mssq!Password3
        #    entrypoint: ["/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "mssq!Password3", "-Q", "CREATE DATABASE OccamsRazor; GO"]


  web:
    build:
      context: .
      dockerfile: OccamsRazorWeb.Dockerfile
    image: occamsrazor.azurecr.io/occamsrazorweb
    container_name: web
    environment:
      - CONNECTION_STRING=data source=databases,1433;Database=master;User Id=sa;Password=mssq!Password3;
    ports:
      - "5000:5000"
    expose:
      - "5000"
    depends_on:
      - databases

  frontend:
    build:
      context: .
      dockerfile: ./OccamsRazorFrontend.Dockerfile
    image: occamsrazor.azurecr.io/occamsrazorfrontend
    container_name: frontend
    ports:
      - "8080:80"
    expose:
      - "8080"
    depends_on:
      - databases
      - web
