# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - occamsrazor

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  NODE_APP_PATH: "./src/OccamsRazor.Frontend"
  ASP_APP_PATH: "./src/OccamsRazor.Web"


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: build docker
      working-directory: ./src
      run: |
        ACR="occamsrazor"
        ACR_URL="$ACR.azurecr.io"
        WEB="$ACR_URL/occamsrazorweb"
        FE="$ARC_URL/occamsrazorfrontend"

        docker-compose build --build-arg "WEB_IMAGE=$WEB" --build-arg "FE_IMAGE=$FE"
        az acr login -n $ARC

        docker push "$WEB"
        docker push "$FE"

    - name: Deploy to Azure Web App
      run: |
        az webapp create

    - name: logout
      run: |
        az logout
