# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - occamsrazor(test)

on:
  push:
    branches:
      - routing-fix
  workflow_dispatch:

env:
  NODE_APP_PATH: "./src/OccamsRazor.Frontend"
  ASP_APP_PATH: "./src/OccamsRazor.Web"


jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present
      working-directory: ${{ env.NODE_APP_PATH }}

    - name: Build with dotnet
      run: dotnet build --configuration Release ${{ env.ASP_APP_PATH }}

    - name: dotnet publish
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp ${{ env.ASP_APP_PATH }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'occamsrazorapi'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_8d97c323a3e94a00bedb1c210a9ec519 }}
        package: ${{env.DOTNET_ROOT}}/myapp

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'occamsrazor'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_f28d425f3d1f4bea92ecd78a12d3bab8 }}
        package: ${{ env.NODE_APP_PATH }}

